### PR TITLE
fix(service-instance): support parameters resolution

### LINKED ISSUE #630: [BUG] Importing XSUAA Service Instance Not Possible When Setting "parameters"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

c40cbe783b21ae494705fa0d6a76ce0e422fd4a3

### What version of the Terraform CLI are you using?

c40cbe783b21ae494705fa0d6a76ce0e422fd4a3

### What type of issue are you facing

bug report

### Describe the bug

When trying to import a XSUAA service instance after creating with parameters, the parameters attribute cannot be imported.
Aside from that it does not seem possible to update a XSUAA service instance (e.g. its name) when creating with an empty parameters JSON ({}). An attempt to do so results in a service broker error. This must be clarified with the XSUAA service owner.

### Expected Behavior

Importing of parameter attributes.

### Steps To Reproduce

1. Adjust the test "TestResourceSubaccountServiceInstance" (happy path - simple service creation with labels) to use a xsuaa with service plan application and add parameters to the resource definition.
2. Run the test: TEST_FORCE_REC=true go test ./... -run TestResourceSubaccountServiceInstance
3. The import error will come up. 

### User's Role Collections

- Subaccount Administrator

### Add screenshots to help explain your problem

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by v0lkc**
## Purpose

* The parameters of a service instance are retrieved based on a "best guess" approach
* The impact of the change is restricted to the import of a service instance. 
* Closes #630 

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type

What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

* Test the code via automated test

```bash
go test ./...
```

## What to Check

Verify that the following are valid:

* Automated tests are executed successfully

## Other Information

n/a

## Checklist for reviewer

The following organizational tasks must be completed before merging this PR:

* [x] The PR is assigned to the Terraform project and a status is set (typically "in review").
* [x] The PR has the matching labels assigned to it.
* [x] The PR has a milestone assigned to it.
* [x] If the PR closes an issue, the issue is referenced.
* [x] Possible follow-up items are created and linked.

### CODE REVIEW

**Review by lechnerc77 — COMMENTED** [review]
@v0lkc the enhancement opens up to fetch the service instance with parameters. However the import logic is not enhanced. 
The discussed solution was to check in the import if the parameters could be read and if not to throw an error that import is not possible.

**Comment by lechnerc77** [comment]
Fixture drift is okay, as a new recording was necessary to reflect the changed HTTP requests for the service instance resource and data source.

**Comment by lechnerc77** [comment]
Inclusive language checks cannot be solved on our end as caused by platform API responses

File: internal/btpcli/facade_services_instance.go [hunk 1]
```diff
@@ -42,19 +42,56 @@ func (f servicesInstanceFacade) List(ctx context.Context, subaccountId string, f
 }
 
 func (f servicesInstanceFacade) GetById(ctx context.Context, subaccountId string, instanceId string) (servicemanager.ServiceInstanceResponseObject, CommandResponse, error) {
-	return doExecute[servicemanager.ServiceInstanceResponseObject](f.cliClient, ctx, NewGetRequest(f.getCommand(), map[string]string{
+	return f.doGet(ctx, map[string]string{
 		"subaccount": subaccountId,
 		"id":         instanceId,
 		"parameters": "false",
```
Comment (kuntzed) [inline internal/btpcli/facade_services_instance.go]: Since the reason to introduce the doGet is to send two requests, one with parameters=false and one with parameters=true, I would prefer to move this into doGet (see below).

File: internal/btpcli/facade_services_instance.go [hunk 2]
```diff
@@ -42,19 +42,56 @@ func (f servicesInstanceFacade) List(ctx context.Context, subaccountId string, f
...
+	return f.doGet(ctx, map[string]string{
 		"subaccount": subaccountId,
 		"name":       instanceName,
 		"parameters": "false",
-	}))
+	})
+}
+
+func (f servicesInstanceFacade) doGet(ctx context.Context, params map[string]string) (sir servicemanager.ServiceInstanceResponseObject, cr CommandResponse, err error) {
+
```
Comment (kuntzed) [inline internal/btpcli/facade_services_instance.go:59]: Let's add

params["parameters"] = "false"

here for symmetry and readability.

File: internal/btpcli/facade_services_instance_test.go [hunk 3]
```diff
@@ -11,7 +11,7 @@ import (
 func TestServicesInstanceFacade_List(t *testing.T) {
 	command := "services/instance"
 
-	subaccountId := "6aa64c2f-38c1-49a9-b2e8-cf9fea769b7f"
+	subaccountId := "59cd458e-e66e-4b60-b6d8-8f219379f9a5"
```
Comment (kuntzed) [inline internal/btpcli/facade_services_instance_test.go]: Is this a real id? In the facade tests it should not matter. Probably does not even need to be a GUID.
Or why did the id change?

**Review by kuntzed — CHANGES_REQUESTED** [review]

File: internal/btpcli/facade_services_instance.go (hunk 1 above)
Comment (lechnerc77) [reply internal/btpcli/facade_services_instance.go]: Moved the setting of params to the `doGet` function with corresponding comments

File: internal/btpcli/facade_services_instance.go (hunk 2 above)
Comment (lechnerc77) [reply internal/btpcli/facade_services_instance.go:59]: Good point - adjusted

File: internal/btpcli/facade_services_instance_test.go (hunk 3 above)
Comment (lechnerc77) [reply internal/btpcli/facade_services_instance_test.go]: That was some glitch during recording, changed it back to original value

**Review by kuntzed — APPROVED** [review]
Thank you very much for providing this workaround.
