### PR TITLE
fix: import of security settings via configuration generation

### LINKED ISSUE #1135: [BUG] Error during import of security settings
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What version of the Terraform provider are you using?

1.14.0

### What version of the Terraform CLI are you using?

1.12.2

### What type of issue are you facing

bug report

### Describe the bug

When executing an import of the resource `btp_subaccount_security_settings` via the command `terraform plan -generate-config-out=generated_config.tf` the following error occurs:

```bash
╷
│ Error: Invalid Attribute Combination
│ 
│   with btp_subaccount_security_settings.sec_setting,
│   on generated_config.tf line 4:
│   (source code not available)
│ 
│ Attribute "iframe_domains_list" cannot be specified when "iframe_domains" is specified
╵
╷
│ Error: Invalid Attribute Combination
│ 
│   with btp_subaccount_security_settings.sec_setting,
│   on generated_config.tf line 5:
│   (source code not available)
│ 
│ Attribute "iframe_domains" cannot be specified when "iframe_domains_list" is specified
```

The resource contains a value for the `iframe_domains`      

### Expected Behavior

The import of the resource via the command `terraform plan -generate-config-out=generated_config.tf` can be executed successfully.

### Steps To Reproduce

1. Create a subaccount
2. Add a iframe_domain to the subaccount security settings
3. Execute the command `terraform plan -generate-config-out=generated_config.tf`

### User's Role Collections

- Subaccount Administrator

### Add screenshots to help explain your problem

n/a

### Additional context

See also: https://github.com/SAP/terraform-exporter-btp/issues/428

### PR DESCRIPTION
**Pull request by lechnerc77**
## Purpose

- Fixes the error when importing a security setting via the `-generate-config-out` parameter
- As a consequence of the fix the attribute `iframe_domains_list` must be used for the import after this fix
- The parameter `iframe_domains` is deprecated and will be removed in the next **major** release
- All existing security settings created via previous provider version are not impacted by this change
- closes #1135

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type

What kind of change does this Pull Request introduce?

```
[X] Bugfix
[ ] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

- Test the code via automated test

```bash
make test
```

## What to Check

Verify that the following are valid:

- Automated tests are executed successfully

## Other Information

n/a

## Checklist for reviewer

The following organizational tasks must be completed before merging this PR:

- [X] The PR status on the Project board is set (typically "in review").
- [X] The PR has the matching labels assigned to it.
- [X] If the PR closes an issue, the issue is referenced.
- [X] Possible follow-up issues are created and linked.

### CODE REVIEW

**Comment by lechnerc77** [comment]
## Validation Scenarios

### Sample configuration

***provider.tf***

```terraform
terraform {
  required_providers {
    btp = {
      source  = "SAP/btp"
      version = "1.XX.0"
    }
  }
}

provider "btp" {
  globalaccount  = "<SUBDOMAIN>"

}
```

**main.tf**

```terraform
resource "btp_subaccount" "my_project" {
  name      = "Retest-Security-Settings-1120"
  subdomain = "retest-security-settings-1120"
  region    = "us10"
}

resource "btp_subaccount_security_settings" "sec_setting" {
  # iframe_domains                         = "https://www.sap.com https://www.sap.com/solutions"
  iframe_domains_list                      = ["https://www.sap.com", "https://www.sap.com/solutions"]
  subaccount_id                            = btp_subaccount.my_project.id
  treat_users_with_same_email_as_same_user = false
}
```

**import.tf**

```terraform
/*
import {
  to = btp_subaccount_security_settings.sec_setting
  id = "<subaccount_ID>"
}
*/
```

### Scenario 1 - Greenfield

We use the new provider and execute the following test cases:

| Test Case | Expected Result | Status |
| --- | --- | --- |
| Create a new security settings with the `iframe_domains` attribute | Both attributes are available in the state | ✅ |
| Create a new security settings with the `iframe_domains_list` attribute | Only the `iframe_domains_list` attribute is filled, the `iframe_domains` is `null` | ✅ |
| Update a security settings with the `iframe_domains` attribute | Both attributes are available in the state | ✅  |
| Update a security settings with the `iframe_domains_list` attribute | Only the `iframe_domains_list` attribute is filled, the `iframe_domains` is `null` | ✅ |
| Import a security settings with the `iframe_domains` attribute | Both attributes are available in the state | ✅ |
| Import a security settings with the `iframe_domains_list` attribute | Only the `iframe_domains_list` attribute is filled, the `iframe_domains` is `null` | ✅ |
| Import via experimental feature (configuration generation) | Only the `iframe_domains_list` attribute is filled, the `iframe_domains` is `null`, generation of configuration succeeds | ✅ |


### Scenario 2 - Regression 1.8.0

- Starting point is provider version 1.8.0.
- Securtity settings are created with this provider. Only `iframe_domains` is available
- Upgrade of provider to version 1.13.0. `iframe_domains_list` is now also available

After upgrade execute the following test cases:

| No | Setup | Expected Result | Status |
| ---| --- | --- | --- |
|1| Execute a `terraform plan`, no further changes| No changes, state only contains the `iframe_domains` attribute | ✅ |
|2| Execute a change via `terraform apply` | Execution plan shows in place update in the `iframe_domains_list` field, state contains data in both `iframe_domains*` attributes after change | ✅ |

Now for each sceanrio upgrade to the new provider and execute the following test cases:

| Setup No | Test Case | Expected Result | Status |
| --- | --- | --- | --- |
| 1 | Execute a `terraform plan` | No changes, state only contains the `iframe_domains` attribute, deprecation message | ✅ |
| 2 | Execute a `terraform plan` | No changes, state only contains tboth `iframe_domains*` attributes, deprecation message | ✅ |
| 1 | Execute a change via `terraform apply` | Execution plan shows in place update in the `iframe_domains_list` field (computed), state contains data in both `iframe_domains*` attributes after change | ✅ |
| 2 | Execute a change via `terraform apply` | Execution plan shows in place update in the `iframe_domains_list` field (computed), information in state for `iframe_domains*` stay unchanged | ✅ |‚


### Scenario 3 - Regression 1.13.0

- Starting point is provider version 1.13.0.
- Securtity settings are created with this provider.

#### Setup

- Setup 1: Create the security settings with the `iframe_domains` attribute.
- Setup 2: Create the security settings with the `iframe_domains_list` attribute.

A manual import of the security settings results in the same state as after creation, namely both `iframe_domains*` attributes are filled.

#### Test Cases

Uprade the provider to the new version and execute the following test cases for each setup:

| Setup | Test Case | Expected Result | Status |
| --- | --- | --- | --- |
| 1 | Execute a `terraform plan` | No changes detected, deprecation message, both attributes filled | ✅ |
| 2 | Execute a `terraform plan` | No changes detected, deprecation message, both attributes filled | ✅ |
| 1 | Execute a change via `terraform apply` | Execution plan shows in place update in the `iframe_domains_list` field (computed), state contains data in both `iframe_domains*` attributes after change | ✅ |
| 2 | Execute a change via `terraform apply` | Execution plan shows in place update in the `iframe_domains` field (computed), state contains data in both `iframe_domains*` attributes after change | ✅ |

### Scenario 4 - Deprecation switch

- Change from deprecated attribute `iframe_domains` to `iframe_domains_list`

| Test Case | Expected Result | Status |
| --- | --- | --- |
| Start from provider version 1.8.0 | Switch is possible without any further action. `terraform plan` shows no deviations | ✅ |
| Start from provider version 1.13.0 | Switch is possible without any further action. `terraform plan` shows no deviations | ✅ |

**Comment by lechnerc77** [comment]
Fixture Drift is expected

File: btp/provider/resource_subaccount_security_settings_test.go [hunk 1]
```diff
@@ -48,12 +48,6 @@ func TestResourceSubaccountSecuritySettings(t *testing.T) {
 						resource.TestCheckResourceAttr("btp_subaccount_security_settings.uut", "iframe_domains_list.1", "https://updated.iframedomain.test"),
 					),
 				},
-				{
-					ResourceName:      "btp_subaccount_security_settings.uut",
-					ImportStateIdFunc: getSecuritySettingsImportStateId("btp_subaccount_security_settings.uut"),
-					ImportState:       true,
-					ImportStateVerify: true,
-				},
```
Comment (ANUGRAHG) [inline btp/provider/resource_subaccount_security_settings_test.go:56]: @lechnerc77 why did we remove this import state test?

Comment (lechnerc77) [reply btp/provider/resource_subaccount_security_settings_test.go:56]: Due to the implemented  change we do no longer support the import via the attribute `iframe_domains`.  Otherwise we would run into the error when the configuration is generated. This is also the reason why we deprecated the field.
The test would fail if executed

Comment (ANUGRAHG) [reply btp/provider/resource_subaccount_security_settings_test.go:56]: This makes perfect sense.. Thank you

**Review by ANUGRAHG — APPROVED** [review]
Looks good to merge.
